export default {
  entrystore: 'https://sandbox.admin.dataportal.se/store',
  urlQueryParameters: true,  //todo: needed/desired?
  namespaces: {
    prof: 'http://www.w3.org/ns/dx/prof/',
    skos: 'http://www.w3.org/2004/02/skos/core#',
    adms: 'http://www.w3.org/ns/adms#',
    inspec: 'https://w3id.org/inspec/datavoc/',
  },
  bundles: [
    'https://static.infra.entryscape.com/suite/latest/templates/dcat3.json',
    'https://static.infra.entryscape.com/suite/latest/templates/rdfs.json', // rdfs bundled with Blocks is minimal
    'https://sandbox.editera.dataportal.se/theme/templates/adms.json',  // todo: update
    'https://sandbox.editera.dataportal.se/theme/templates/prof.json',  // todo: update
    'https://sandbox.editera.dataportal.se/theme/templates/terms.json',  // todo: update
    'https://static.infra.entryscape.com/suite/latest/templates/rdfs.json',
  ],
  clicks: {
    spec: './specification.html',
    organization: './organisation.html',
    concept: './concept.html',
    conceptScheme: './terminology.html', // todo: phase out in favour of terminology
    terminology: './terminology.html',
    class: './class.html',
    def: './class.html',  // todo: phase out, some are property
    vocabulary: './class.html',  // todo: phase out, some are property
    property: './property.html',
    ap: './ap.html',
    shape: './ap.html',
    specDetails: './ap.html', // todo: phase out in favour of
    datavoc: './datavoc.html',
    dataset: './dataset.html', // todo: point to the canonical one
  },
  type2template: {
    'prof:Profile': 'prof:Profile',
    'dcterms:Standard': 'prof:Profile',
    'skos:ConceptScheme': 'skosmos:conceptSchemeWithPublisher',
    'skos:Concept': 'editera:Concept',
    'rdfs:Class': 'rdfs:Class',
    'rdf:Property': 'rdf:Property',
  },
  routes: [ //todo: these are likely broken, not sure esc_uri is needed
    {
      regex: /\/def.html\?esc_uri=(.+)/,
      uri: 1,
      constraints: {
        'rdf:type': ['skos:Concept', 'skos:ConceptScheme'],
      },
    },
    {
      regex: /\/def.html#esc_uri=(.+)/,
      uri: 1,
      constraints: {
        'rdf:type': ['skos:Concept', 'skos:ConceptScheme'],
      },
    },
    {
      regex: /\/spec.html\?esc_uri=(.+)/,
      uri: 1,
      constraints: {
        'rdf:type': ['prof:Profile', 'dcterms:Standard'],
      },
    },
    {
      regex: /\/ap.html\?esc_uri=(.+)/,
      uri: 1,
      constraints: {
        'rdf:type': ['prof:Profile', 'dcterms:Standard'],
      },
    },
    {
      regex: /\/ap.html\?esc_shape=(.+)/,
      lookup: 1,
      lookupURI: 'dcterms:hasPart',
      constraints: {
        'rdf:type': ['prof:Profile', 'dcterms:Standard'],
      },
    },
  ],
  page_language: 'sv',
  nls: {
    sv: {
      datavoc: {
        datavoc: 'Datavokabulär',
        datavocUri: 'Adress för datavokabulären',
        classesInDatavoc: 'I datavokabulären ingår {{PLURAL:${count}|${count} klass|${count} klasser}}',
        propertiesInDatavoc: 'I datavokabulären ingår {{PLURAL:${count}|${count} egenskap|${count} egenskaper}}',
        reusedNumberInfo: '{{PLURAL:${count}|Interoperabel specifikation|Interoperabla specifikationer}} som använder denna datavokabulär.',
        usageInSpecIntro: 'Lite fast text som förklarar övergången till "användning i specifikationer".',
      },
      class: {
        class: 'Klass',
        classUri: 'Adress för klassen',
        reusedNumberInfo: '{{PLURAL:${count}|Interoperabel specifikation|Interoperabla specifikationer}} som använder denna klass.',
        usageInSpecIntro: 'Lite fast text som förklarar övergången till "användning i specifikationer".',
      },
      property: {
        property: 'Egenskap',
        propertyUri: 'Adress för egenskapen',
        reusedNumberInfo: '{{PLURAL:${count}|Interoperabel specifikation|Interoperabla specifikationer}} som använder denna egenskap.',
        usageInSpecIntro: 'Lite fast text som förklarar övergången till "användning i specifikationer".',
      },
      conceptScheme: {
        conceptScheme: 'Terminologi',
        reusedInSpecification: 'Återanvänds i specifikation',
        terminologyUri: 'Adress för terminologin',
        reusedNumberInfo: '{{PLURAL:${count}|Interoperabel specifikation|Interoperabla specifikationer}} som använder denna terminologi.',
        topConceptsInTerminology: 'I terminologin ingår ${count} begrepp på översta nivån',
        conceptCount: 'Totalt antal begrepp',
        usageInSpecIntro: 'Lite fast text som förklarar övergången till "användning i specifikationer".',
      },
      concept: {
        concept: 'Begrepp',
        altLabel: 'Alternativa termer',
        conceptUri: 'Adress för begreppet',
        isTopConcept: 'Detta är ett begrepp på översta nivån',
        noNarrowerConcepts: 'Har inga underordnade begrepp',
        noRelatedConcepts: 'Har inga relaterade begrepp',
        broaderConcepts: 'Överordnade begrepp',
        narrowerConcepts: 'Underordnade begrepp',
        relatedConcepts: 'Relaterade begrepp',
        matchingConcepts: 'Matchande begrepp (I andra terminologier)',
        memberOfTerminology: 'Ingår i terminologi',
      },
      general: {
        details: 'Detaljer',
        description: 'Beskrivning',
        download: 'Ladda ner',
        loading: 'Laddar resultat…',
        introducedInSpecification: 'Introduceras i specifikation',
        usedInSpecification: 'Används i {{PLURAL:${count}|1 interoperabel specifikation|${count} interoperabla specifikationer}}',
        isPartOfDatavoc: 'Ingår i datavokabulär',
        downloadMetadataRdfXml: 'Ladda ner metadata som RDF/XML',
        downloadMetadataTurtle: 'Ladda ner metadata som TURTLE',
        downloadMetadataJsonLd: 'Ladda ner metadata som JSON-LD',
      },
      spec: {
        specificationUri: 'Adress för specifikation',
        exploreAP: 'Utforska applikationsprofil',
        classesAndProperties: 'Klasser och egenskaper',
        cpIntroduced: '{{PLURAL:${count}|1 introducerad Klass eller Egenskap|${count} introducerade Klasser och Egenskaper}} (I denna specifikation)',
        cpReused: '{{PLURAL:${count}|1 återanvänd Klass eller Egenskap|${count} återanvända Klasser och Egenskaper}} (Från andra specifikationer)',
        resources: 'Resurser',
        rIntroduced: 'Introducerade (I denna specifikation)',
        rReused: 'Återanvända (Från andra specifikationer)',
        moreInformation: 'Mer information',
        lessInformation: 'Mindre information',
        thisSpecificationHasNoResources: 'Denna specifikation har inga resurser.',
        thisSpecificationHasNoReusedResources: 'Denna specifikation har inga återanvända resurser.',
        goToResource: 'Gå till resurs',
        role: 'Roll',
        reusedFrom: 'Återanvänd ifrån',
        aboutTheSpecification: 'Om specifikationen',
        foundationalInspec: 'Interoperabel basspecifikation',
        profileInspec: 'Interoperabel profilspecifikation',
        nonInspec: 'Specifikation',
        conformanceNumberInfo: '{{PLURAL:${count}|Datamängd|Datamängder}} följer denna specifikation.',
        grunddataConformanceNumberInfo: 'Varav {{PLURAL:${count}|${count}|${count} stycken}} är nationell grunddatamängd:',
      },
      respec: {
        backToTheOverview: 'Tillbaka till översikten',
        detailsMoreDetailsOnThisDocument: 'Fler detaljer om detta dokument',
        profileOf: 'Profil av',
        preferredIdentifier: 'Föredragen identifierare',
        createdBy: 'Skapad av',
        stableAddressToThisVersion: 'Stabil adress för denna version',
        publicationDate: 'Publiceringsdatum',
        modificationDate: 'Ändringsdatum',
        latestVersion: 'Senaste version',
        lastVersion: 'Föregående version',
        nextVersion: 'Nästa version',
        diagram: 'Diagram',
      },
    },
    en: {
      datavoc: {
        datavoc: 'Data Vocabulary',
        datavocUri: 'Uri for the data vocabulary',
        classesInDatavoc: 'The data vocabulary includes {{PLURAL:${count}|${count} class|${count} classes}}',
        propertiesInDatavoc: 'The data vocabulary includes {{PLURAL:${count}|${count} property|${count} properties}}',
        reusedNumberInfo: '{{PLURAL:${count}|Interoperable specification|Interoperable specifications}} that use this data vocabulary.',
        usageInSpecIntro: 'Some fixed text explaining the transition to "used in specifications".',
      },
      class: {
        class: 'Class',
        classUri: 'Uri for the class',
        reusedNumberInfo: '{{PLURAL:${count}|Interoperable specification|Interoperable specifications}} that use this class.',
        usageInSpecIntro: 'Some fixed text explaining the transition to "used in specifications".',
      },
      property: {
        property: 'Property',
        propertyUri: 'Uri for the property',
        reusedNumberInfo: '{{PLURAL:${count}|Interoperable specification|Interoperable specifications}} that use this property.',
        usageInSpecIntro: 'Some fixed text explaining the transition to "used in specifications".',
      },
      conceptScheme: {
        conceptScheme: 'Terminology',
        reusedInSpecification: 'Reused in specification',
        terminologyUri: 'URI for the terminology',
        reusedNumberInfo: '{{PLURAL:${count}|Interoperable specification|Interoperable specifications}} that use this terminology.',
        topConceptsInTerminology: 'The terminology includes {{PLURAL:${count}|${count} concept|${count} concepts}} on the top level',
        conceptCount: 'Total number of concepts',
        usageInSpecIntro: 'Some fixed text explaining the transition to "used in specifications".',
      },
      concept: {
        concept: 'Concept',
        altLabel: 'Alternative labels',
        conceptUri: 'Uri for the concept',
        isTopConcept: 'This is a top level concept',
        noNarrowerConcepts: 'No narrower concepts',
        noRelatedConcepts: 'No related concepts',
        broaderConcepts: 'Broader concepts',
        narrowerConcepts: 'Narrower concepts',
        relatedConcepts: 'Related concepts',
        matchingConcepts: 'Matching concepts (In other terminologies)',
        memberOfTerminology: 'Member of terminology',
      },
      general: {
        details: 'Details',
        description: 'Description',
        download: 'Download',
        loading: 'Loading results…',
        introducedInSpecification: 'Introduced in specification',
        usedInSpecification: 'Used in ${count} interoperable {{PLURAL:${count}|specification|specifications}}',
        isPartOfDatavoc: 'Is part of data vocabulary',
        downloadMetadataRdfXml: 'Download metadata as RDF/XML',
        downloadMetadataTurtle: 'Download metadata as TURTLE',
        downloadMetadataJsonLd: 'Download metadata as JSON-LD',
      },
      spec: {
        specificationUri: 'URI for the specification',
        exploreAP: 'Explore the application profile',
        classesAndProperties: 'Classes and properties',
        cpIntroduced: '{{PLURAL:${count}|1 introduced Class or Property|${count} introduced Classes and Properties}} (In this specification)',
        cpReused: '{{PLURAL:${count}|1 reused Class or Property|${count} reused Classes and Properties}} (From other specifications)',
        resources: 'Resources',
        rIntroduced: 'Introduced (In this specification)',
        rReused: 'Reused (From other specifications)',
        moreInformation: 'More information',
        lessInformation: 'Less information',
        thisSpecificationHasNoResources: 'This specification has no resources.',
        thisSpecificationHasNoReusedResources: 'This specification has no reused resources.',
        goToResource: 'Go to resource',
        role: 'Role',
        reusedFrom: 'Reused from',
        aboutTheSpecification: 'About the specification',
        foundationalInspec: 'Foundational interoperable specification',
        profileInspec: 'Profile interoperable specification',
        nonInspec: 'Specification',
        conformanceNumberInfo: '{{PLURAL:${count}|Dataset|Datasets}} conform to this specification.',
        grunddataConformanceNumberInfo: 'Of which {{PLURAL:${count}|${count}|${count}}} are national basic datasets:',
      },
      respec: {
        backToTheOverview: 'Back to the overview',
        detailsMoreDetailsOnThisDocument: 'More details about this document',
        profileOf: 'Profile of',
        preferredIdentifier: 'Preferred identifier',
        createdBy: 'Created by',
        stableAddressToThisVersion: 'Stable address to this version',
        publicationDate: 'Publication date',
        modificationDate: 'Modification date',
        latestVersion: 'Latest version',
        lastVersion: 'Previous version',
        nextVersion: 'Next version',
        diagram: 'Diagram',
      },
    },
  },
};
