export default {
  entrystore: 'https://sandbox.admin.dataportal.se/store',
  urlQueryParameters: true,  //todo: needed/desired?
  namespaces: {
    prof: 'http://www.w3.org/ns/dx/prof/',
    skos: 'http://www.w3.org/2004/02/skos/core#',
    adms: 'http://www.w3.org/ns/adms#',
    inspec: 'https://w3id.org/inspec/datavoc/',
  },
  bundles: [
    'https://static.infra.entryscape.com/suite/latest/templates/dcat3.json',
    'https://sandbox.editera.dataportal.se/theme/templates/adms.json',  // todo: update
    'https://sandbox.editera.dataportal.se/theme/templates/prof.json',  // todo: update
    'https://static.infra.entryscape.com/suite/latest/templates/rdfs.json',
  ],
  clicks: {
    spec: './specification.html',
    organization: './organisation.html',
    concept: './concepts.html',
    conceptScheme: './terminology.html',
    terminology: './terminology.html', // todo: phase out in favour of conceptScheme
    class: './class.html',
    def: './class.html',  // todo: phase out, some are property
    vocabulary: './class.html',  // todo: phase out, some are property
    property: './property.html',
    ap: './ap.html',
    shape: './ap.html',
    specDetails: './ap.html', // todo: phase out in favour of
    datavoc: './datavoc.html',
  },
  routes: [ //todo: these are likely broken, not sure esc_uri is needed
    {
      regex: /\/def.html\?esc_uri=(.+)/,
      uri: 1,
      constraints: {
        'rdf:type': ['skos:Concept', 'skos:ConceptScheme'],
      },
    },
    {
      regex: /\/def.html#esc_uri=(.+)/,
      uri: 1,
      constraints: {
        'rdf:type': ['skos:Concept', 'skos:ConceptScheme'],
      },
    },
    {
      regex: /\/spec.html\?esc_uri=(.+)/,
      uri: 1,
      constraints: {
        'rdf:type': ['prof:Profile', 'dcterms:Standard'],
      },
    },
    {
      regex: /\/ap.html\?esc_uri=(.+)/,
      uri: 1,
      constraints: {
        'rdf:type': ['prof:Profile', 'dcterms:Standard'],
      },
    },
    {
      regex: /\/ap.html\?esc_shape=(.+)/,
      lookup: 1,
      lookupURI: 'dcterms:hasPart',
      constraints: {
        'rdf:type': ['prof:Profile', 'dcterms:Standard'],
      },
    },
  ],
  page_language: 'sv',
  nls: {
    sv: {
      datavoc: {
        datavoc: 'Datavokabulär',
        datavocUri: 'Adress för datavokabulären',
        classesInDatavoc: 'I datavokabulären ingår {{PLURAL:${count}|${count} klass|${count} klasser}}',
        propertiesInDatavoc: 'I datavokabulären ingår {{PLURAL:${count}|${count} egenskap|${count} egenskaper}}',
        reusedNumberInfo: '{{PLURAL:${count}|Interoperabel specifikation|Interoperabla specifikationer}} som använder denna datavokabulär.',
        usageInSpecIntro: 'Lite fast text som förklarar övergången till "använding i specifikationer".',
      },
      conceptScheme: {
        conceptScheme: 'Terminologi',
        reusedInSpecification: 'Återanvänds i specifikation',
        terminologyUri: 'Adress för terminologin',
        reusedNumberInfo: '{{PLURAL:${count}|Interoperabel specifikation|Interoperabla specifikationer}} som använder denna terminologi.',
        conceptsInTerminology: 'I terminologin ingår ${count} begrepp',
        usageInSpecIntro: 'Lite fast text som förklarar övergången till "använding i specifikationer".',
      },
      concept: {
        concept: 'Begrepp',
        memberOfTerminology: 'Ingår i terminologi',
      },
      general: {
        details: 'Detaljer',
        download: 'Ladda ner',
        introducedInSpecification: 'Introduceras i specifikation',
        usedInSpecification: 'Används i {{PLURAL:${count}|1 interoperabel specifikation|${count} interoperabla specifikationer}}',
        downloadMetadataRdfXml: 'Ladda ner metadata som RDF/XML',
        downloadMetadataTurtle: 'Ladda ner metadata som TURTLE',
        downloadMetadataJsonLd: 'Ladda ner metadata som JSON-LD',
      },
      spec: {
        exploreTheSpecification: 'Utforska specifikationen',
        classesAndProperties: 'Klasser och egenskaper',
        cpIntroduced: 'Introducerade',
        cpReused: 'Återanvända',
        resources: 'Resurser',
        rIntroduced: 'Introducerade',
        rReused: 'Återanvända',
        moreInformation: 'Mer information',
        lessInformation: 'Mindre information',
        thisSpecificationHasNoResources: 'Denna specifikation har inga resurser.',
        thisSpecificationHasNoReusedResources: 'Denna specifikation har inga återanvända resurser.',
        goToResource: 'Gå till resurs',
        role: 'Roll',
        reusedFrom: 'Återanvänd ifrån',
        aboutTheSpecification: 'Om specifikationen',
      },
      respec: {
        backToTheOverview: 'Tillbaka till översikten',
        detailsMoreDetailsOnThisDocument: 'Fler detaljer om detta dokument',
        profileOf: 'Profil av',
        preferredIdentifier: 'Föredragen identifierare',
        createdBy: 'Skapad av',
        stableAddressToThisVersion: 'Stabil adress för denna version',
        publicationDate: 'Publiceringsdatum',
        modificationDate: 'Ändringsdatum',
        latestVersion: 'Senaste version',
        lastVersion: 'Föregående version',
        nextVersion: 'Nästa version',
        diagram: 'Diagram',
      },
    },
    en: {
      datavoc: {
        datavoc: 'Data Vocabulary',
        datavocUri: 'Uri for the data vocabulary',
        classesInDatavoc: 'The data vocabulary includes {{PLURAL:${count}|${count} class|${count} classes}}',
        propertiesInDatavoc: 'The data vocabulary includes {{PLURAL:${count}|${count} property|${count} properties}}',
        reusedNumberInfo: '{{PLURAL:${count}|Interoperable specification|Interoperable specifications}} that use this data vocabulary.',
        usageInSpecIntro: 'Some fixed text explaining the transition to "used in specifications".',
      },
      conceptScheme: {
        conceptScheme: 'Terminology',
        reusedInSpecification: 'Reused in specification',
        terminologyUri: 'URI for the terminology',
        reusedNumberInfo: '{{PLURAL:${count}|Interoperable specification|Interoperable specifications}} that use this terminology.',
        conceptsInTerminology: 'The terminology includes {{PLURAL:${count}|${count} concept|${count} concepts}}',
        usageInSpecIntro: 'Some fixed text explaining the transition to "used in specifications".',
      },
      concept: {
        concept: 'Concept',
        memberOfTerminology: 'Member of terminology',
      },
      general: {
        details: 'Details',
        download: 'Download',
        introducedInSpecification: 'Introduced in specification',
        usedInSpecification: 'Used in ${count} interoperable {{PLURAL:${count}|specification|specifications}}',
        downloadMetadataRdfXml: 'Download metadata as RDF/XML',
        downloadMetadataTurtle: 'Download metadata as TURTLE',
        downloadMetadataJsonLd: 'Download metadata as JSON-LD',
      },
      spec: {
        exploreTheSpecification: 'Explore the specification',
        classesAndProperties: 'Classes and properties',
        cpIntroduced: 'Introduced',
        cpReused: 'Reused',
        resources: 'Resources',
        rIntroduced: 'Introduced',
        rReused: 'Reused',
        moreInformation: 'More information',
        lessInformation: 'Less information',
        thisSpecificationHasNoResources: 'This specification has no resources.',
        thisSpecificationHasNoReusedResources: 'This specification has no reused resources.',
        goToResource: 'Go to resource',
        role: 'Role',
        reusedFrom: 'Reused from',
        aboutTheSpecification: 'About the specification',
      },
      respec: {
        backToTheOverview: 'Back to the overview',
        detailsMoreDetailsOnThisDocument: 'More details about this document',
        profileOf: 'Profile of',
        preferredIdentifier: 'Preferred identifier',
        createdBy: 'Created by',
        stableAddressToThisVersion: 'Stable address to this version',
        publicationDate: 'Publication date',
        modificationDate: 'Modification date',
        latestVersion: 'Latest version',
        lastVersion: 'Previous version',
        nextVersion: 'Next version',
        diagram: 'Diagram',
      },
    },
  },
};
